"""Generate the credit and provenance document from the registry.

Attribution is a build step rather than a courtesy: this project is a consumer of other
people's decades of fieldwork, and a hand-maintained credits page drifts.
"""

from typing import TYPE_CHECKING

from migratlas.catalog.loader import load

if TYPE_CHECKING:
    from collections.abc import Iterable
    from pathlib import Path

    from migratlas.catalog.models import Source

HEADER = """<!-- Generated by `migratlas catalog provenance`. Do not edit by hand. -->

# Data provenance and credit

Every source below is registered in
[`src/migratlas/catalog/registry.yaml`](../../src/migratlas/catalog/registry.yaml) with
its licence, citation and sensitivity classification. Nothing may be ingested that is
not described there.

None of this data is ours. Cloning this repository gives you the code, not the data —
each source carries its own terms.
"""


def render() -> str:
    """Render the whole document."""
    sources = load()
    parts = [HEADER, _summary_table(sources.values()), ""]
    parts.extend(_source_section(source) for source in sources.values())
    return "\n".join(parts)


def _summary_table(sources: Iterable[Source]) -> str:
    rows = [
        "## At a glance",
        "",
        "| Source | Evidence | Realm | Licence | Redistribution |",
        "| --- | --- | --- | --- | --- |",
    ]
    for source in sources:
        redist = "permitted" if source.redistribution.allowed else "**not permitted**"
        kind = f"`{source.evidence_type}`" if source.provides_evidence else "driver only"
        rows.append(
            f"| [{source.title}]({source.landing_page}) | {kind} "
            f"| `{source.realm}` | {source.licence} | {redist} |"
        )
    return "\n".join(rows)


def _source_section(source: Source) -> str:
    kind = (
        f"**evidence type** `{source.evidence_type}` · **realm** `{source.realm}`"
        f" · **taxon scope** `{source.taxon_scope}`"
        if source.provides_evidence
        # A wind field is not evidence about an animal and has no taxon to scope. Saying that
        # explicitly is better than printing `None` twice.
        else f"**drivers only**, no evidence rows · **realm** `{source.realm}`"
    )
    lines = [
        f"## {source.title}",
        "",
        f"- **id** `{source.id}`",
        f"- {kind}",
        f"- **landing page** {source.landing_page}",
    ]
    if source.doi:
        lines.append(f"- **DOI** [{source.doi}](https://doi.org/{source.doi})")

    licence = f"[{source.licence}]({source.licence_url})" if source.licence_url else source.licence
    lines.append(f"- **licence** {licence}")

    redist = source.redistribution
    verdict = "permitted" if redist.allowed else "**not permitted**"
    detail = [verdict]
    if redist.attribution_required:
        detail.append("attribution required")
    if redist.commercial_use is False:
        detail.append("non-commercial only")
    elif redist.commercial_use is None:
        detail.append("commercial use unstated")
    lines.append(f"- **redistribution** {', '.join(detail)}")
    if redist.notes:
        lines.append(f"  - {redist.notes}")

    lines.append(f"- **sensitivity** `{source.default_sensitivity}` by default")
    for rule in source.taxon_sensitivity:
        scope = " · ".join(filter(None, [str(rule.evidence_type or ""), str(rule.realm or "")]))
        suffix = f" ({scope})" if scope else ""
        lines.append(
            f"  - GBIF `{rule.taxon_key}` → `{rule.sensitivity}`{suffix}: {rule.rationale}"
        )

    if source.credential:
        lines.append(f"- **credential** `MIGRATLAS_CRED_{source.credential.upper()}` required")

    lines += ["", "**Cite as**", "", f"> {source.citation.strip()}", ""]

    if source.caveats:
        lines += ["**Caveats**", "", source.caveats.strip(), ""]

    return "\n".join(lines)


def write(destination: Path) -> int:
    """Write the document. Returns bytes written."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    text = render()
    destination.write_text(text, encoding="utf-8")
    return len(text)
